### ISSUE TITLE
必须滑动大于屏幕一半才生效，这个机制手感很不好

### ISSUE THREAD

**Issue by maltsugar** [bestDew/ZKCycleScrollView#1]
可以试下其他的手感，这个必须滑动很多才生效，用着不舒服，希望改进一下layout

**Comment by bestDew** [comment]
感谢建议！已改进

**Comment by bestDew** [comment]
> 可以试下其他的手感，这个必须滑动很多才生效，用着不舒服，希望改进一下layout

感谢建议！已改进
